# Generated by Django 4.2.30 on 2026-06-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("agency_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=32)),
                ("state", models.CharField(max_length=2)),
                ("num_producers", models.IntegerField()),
                ("years_in_business", models.IntegerField()),
                ("estimated_book_size_usd", models.BigIntegerField()),
                ("stage", models.CharField(max_length=32)),
                ("signed_up_date", models.DateField(null=True)),
                ("last_login_date", models.DateField(null=True)),
                ("quotes_created", models.IntegerField(default=0)),
                ("quotes_submitted", models.IntegerField(default=0)),
                ("deals_closed", models.IntegerField(default=0)),
                ("last_contacted_date", models.DateField(null=True)),
                ("hubspot_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="OutreachAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("priority", models.IntegerField()),
                ("action_type", models.CharField(max_length=64)),
                ("reason", models.TextField()),
                ("suggested_copy", models.TextField(blank=True)),
                ("needs_human", models.BooleanField(default=False)),
                ("further_action", models.TextField(blank=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_actions",
                        to="app.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField()),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.lead",
                    ),
                ),
            ],
        ),
    ]
