"""Add ``Lead.tenant``: the user id that owns a lead.

Nullable-first, per the column rule in CLAUDE.md: the column lands empty, the
book is assigned with ``manage.py backfill_lead_tenant``, and constraining it
(NOT NULL, and dropping the ``tenant__isnull`` arm of ``scope_to_tenant``) is a
separate, later, human-reviewed decision.

HOT TABLE -- ``lead``. On Postgres this is one ALTER TABLE: adding a nullable
column with no default is metadata-only, but the FK constraint and the FK's
index still take ACCESS EXCLUSIVE / SHARE for the length of the statement. Both
are fast here because the new column is entirely NULL (nothing to validate, an
empty index to build), so it is one short lock rather than a rewrite -- still,
this migration wants human review before it runs anywhere real.
"""

# Generated by Django 4.2.30 on 2026-09-16 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
