# Generated by Django 4.2.30 on 2026-07-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reviewdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('api_key_url', models.URLField()),
                ('api_key_label', models.CharField(max_length=100)),
                ('api_key_prefix', models.CharField(blank=True, max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('context_window', models.IntegerField()),
                ('default_max_tokens', models.IntegerField(default=500)),
                ('input_price_per_mtok_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('output_price_per_mtok_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tier', models.CharField(blank=True, max_length=32)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='app.llmprovider')),
            ],
            options={
                'ordering': ['sort_order', 'model_id'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tokens', models.IntegerField()),
                ('encrypted_api_key', models.BinaryField(blank=True, null=True)),
                ('key_last_four', models.CharField(blank=True, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.llmmodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.llmprovider')),
            ],
        ),
        migrations.AddConstraint(
            model_name='llmconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('pk', 1)), name='single_llm_configuration'),
        ),
    ]
