# Generated by Django 4.2.30 on 2026-07-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_logintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedOutreachKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('action_type', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_by', models.EmailField(blank=True, default='', max_length=254)),
                ('revoked_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-dismissed_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('editor', models.EmailField(blank=True, default='', max_length=254)),
                ('before_text', models.TextField()),
                ('after_text', models.TextField()),
                ('diff_ops', models.JSONField(blank=True, default=list)),
                ('chars_added', models.IntegerField(default=0)),
                ('chars_removed', models.IntegerField(default=0)),
                ('similarity', models.FloatField(default=1.0)),
                ('committed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='dismiss_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='edited_copy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='rule_trace',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='snooze_activity_after',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='snooze_trigger',
            field=models.CharField(blank=True, choices=[('tomorrow', 'Tomorrow'), ('in_3_days', 'In 3 days'), ('next_week', 'Next week'), ('custom', 'Custom date'), ('on_activity', 'When they do something')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='snooze_until',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='outreachaction',
            name='verification',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='outreachaction',
            index=models.Index(fields=['status', 'priority', 'lead'], name='oa_queue_order'),
        ),
        migrations.AddIndex(
            model_name='outreachaction',
            index=models.Index(fields=['status', '-status_changed_at'], name='oa_done_order'),
        ),
        migrations.AddField(
            model_name='outreachedit',
            name='outreach_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='app.outreachaction'),
        ),
        migrations.AddField(
            model_name='dismissedoutreachkey',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_keys', to='app.lead'),
        ),
        migrations.AddField(
            model_name='dismissedoutreachkey',
            name='source_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.outreachaction'),
        ),
    ]
