# Generated by Django 4.2.30 on 2026-07-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_triage_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachaction',
            name='trace_run_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AddConstraint(
            model_name='outreachaction',
            constraint=models.UniqueConstraint(condition=models.Q(('trace_run_id', ''), _negated=True), fields=('trace_run_id', 'lead'), name='oa_one_row_per_lead_per_run'),
        ),
    ]
