# Generated by Django 4.2.30 on 2026-07-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_triage_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachaction',
            name='trace_run_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
    ]
