# Generated by Django 4.2.30 on 2026-08-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_outreachaction_trace_run_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_name', models.CharField(max_length=100)),
                ('ae_email', models.EmailField(max_length=254)),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('synthetic', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slot_start'],
            },
        ),
        migrations.CreateModel(
            name='AgentLeadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_run_id', models.CharField(db_index=True, max_length=36)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('claimed_by', models.CharField(blank=True, default='', max_length=32)),
                ('claim_epoch', models.IntegerField(default=0)),
                ('steps_used', models.IntegerField(default=0)),
                ('tool_calls_used', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('kind', models.CharField(max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('request_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('result_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='OutboundSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_sha256', models.CharField(max_length=64)),
                ('channel', models.CharField(default='console', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='approved_body_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='approved_copy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='voided_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outreachaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed'), ('sent', 'Sent')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='outreach_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='app.outreachaction'),
        ),
        migrations.AddConstraint(
            model_name='reviewdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('select_existing', 'propose_new'))), fields=('outreach_action',), name='rd_one_resolution_per_action'),
        ),
        migrations.AddConstraint(
            model_name='reviewdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('approve_send', 'reject_send')), ('voided_at__isnull', True)), fields=('outreach_action',), name='rd_one_live_send_per_action'),
        ),
        migrations.AddField(
            model_name='outboundsend',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reviewdecision'),
        ),
        migrations.AddField(
            model_name='outboundsend',
            name='outreach_action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_send', to='app.outreachaction'),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='lead_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.agentleadrun'),
        ),
        migrations.AddField(
            model_name='agentleadrun',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='app.lead'),
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('lead_run', 'seq'), name='astep_one_seq_per_run'),
        ),
        migrations.AddIndex(
            model_name='agentleadrun',
            index=models.Index(fields=['trace_run_id', 'status'], name='alr_resume_scan'),
        ),
        migrations.AddConstraint(
            model_name='agentleadrun',
            constraint=models.UniqueConstraint(fields=('trace_run_id', 'lead'), name='alr_one_run_per_lead_per_trace'),
        ),
    ]
