# Generated by Django 4.2.30 on 2026-08-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_agent_loop"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action_type", models.CharField(max_length=64)),
                ("priority", models.IntegerField()),
                ("reason", models.TextField()),
                ("rule_trace", models.JSONField(blank=True, default=dict)),
                ("advisory_text", models.TextField(blank=True, default="")),
                (
                    "advisory_status",
                    models.CharField(
                        choices=[
                            ("ok", "Advisory present"),
                            ("disabled", "Advisory not enabled"),
                            ("ungrounded", "Advisory dropped — ungrounded"),
                            ("provider_error", "Advisory dropped — provider error"),
                        ],
                        default="disabled",
                        max_length=32,
                    ),
                ),
                ("verification", models.JSONField(blank=True, default=dict)),
                ("provider", models.CharField(blank=True, default="", max_length=32)),
                ("model_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "trace_run_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=36
                    ),
                ),
                ("dismissed", models.BooleanField(default=False)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="app.lead",
                    ),
                ),
                (
                    "open_outreach_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.outreachaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["lead", "-created_at"], name="la_lead_recent")
                ],
            },
        ),
    ]
