# Generated by Django 4.2.30 on 2026-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_agent_loop"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("model_id", models.CharField(max_length=100)),
                (
                    "trace_run_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=36
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
