# Generated by Django 4.2.30 on 2026-08-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_agent_loop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='draft', max_length=16)),
                ('scope', models.JSONField(default=dict)),
                ('active_sentinel', models.BooleanField(default=True, null=True)),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished_by', models.EmailField(blank=True, default='', max_length=254)),
                ('trace_run_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('classify_ms', models.IntegerField(blank=True, default=None, null=True)),
                ('read_provider', models.CharField(blank=True, default='', max_length=32)),
                ('read_model', models.CharField(blank=True, default='', max_length=128)),
                ('generate_provider', models.CharField(blank=True, default='', max_length=32)),
                ('generate_model', models.CharField(blank=True, default='', max_length=128)),
                ('read_cost_estimate_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('read_cost_actual_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('generate_cost_estimate_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('generate_cost_actual_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('discarded_suggestions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SavedScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('filters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RunLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_priority', models.IntegerField()),
                ('rules_action', models.CharField(max_length=64)),
                ('rules_reason', models.TextField()),
                ('rule_trace', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(db_index=True, max_length=128)),
                ('effective_priority', models.IntegerField()),
                ('effective_action', models.CharField(max_length=64)),
                ('effective_reason', models.TextField()),
                ('already_queued', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('generation_error', models.CharField(blank=True, default='', max_length=64)),
                ('suggestion', models.JSONField(blank=True, default=dict)),
                ('suggestion_state', models.CharField(default='none', max_length=16)),
                ('suggestion_decided_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('suggestion_decided_by', models.EmailField(blank=True, default='', max_length=254)),
                ('generated_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_lead', to='app.outreachaction')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.lead')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_leads', to='app.plannerrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='plannerrun',
            constraint=models.UniqueConstraint(condition=models.Q(('active_sentinel', True)), fields=('active_sentinel',), name='pr_one_active_run'),
        ),
        # `active_sentinel__isnull=False` reads as redundant next to
        # `active_sentinel=True` and is not: Django renders the latter as the
        # bare column, so without the IS NOT NULL conjunct the first disjunct is
        # NULL for a NULL sentinel, `NULL OR FALSE` is NULL, and SQL rejects a
        # row only on FALSE. Dropping it silently deletes half the constraint.
        migrations.AddConstraint(
            model_name='plannerrun',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active_sentinel', True), ('active_sentinel__isnull', False), ('status__in', ('draft', 'classified', 'read', 'generated'))), models.Q(('active_sentinel__isnull', True), ('status__in', ('completed', 'discarded'))), _connector='OR'), name='pr_sentinel_matches_status'),
        ),
        migrations.AddIndex(
            model_name='runlead',
            index=models.Index(fields=['run', 'effective_priority', 'lead'], name='rl_selection_order'),
        ),
        migrations.AddConstraint(
            model_name='runlead',
            constraint=models.UniqueConstraint(fields=('run', 'lead'), name='rl_one_row_per_lead_per_run'),
        ),
    ]
