# Generated by Django 4.2.30 on 2026-08-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_providertrace"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentstep",
            name="provider_trace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="app.providertrace",
            ),
        ),
        migrations.CreateModel(
            name="ProviderTraceContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.TextField(blank=True, default="")),
                ("reasoning", models.TextField(blank=True, default="")),
                ("response", models.TextField(blank=True, default="")),
                (
                    "trace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="app.providertrace",
                    ),
                ),
            ],
        ),
    ]
