# Generated by Django 4.2.30 on 2026-09-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_agentstep_provider_trace_providertracecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outreachaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("snoozed", "Snoozed"),
                    ("dismissed", "Dismissed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(
            name="OutboundSend",
        ),
    ]
