# Generated by Django 4.2.30 on 2026-09-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_delete_agent_loop"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="outreachaction",
            name="oa_one_row_per_lead_per_run",
        ),
        migrations.RemoveField(
            model_name="outreachaction",
            name="trace_run_id",
        ),
    ]
