"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (KEY=value lines) without requiring python-dotenv
_env_file = BASE_DIR / ".env"
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _k, _, _v = _line.partition("=")
            os.environ.setdefault(_k.strip(), _v.strip())

# LLM provider/model/key selection lives in the database (LLMConfiguration,
# see project/app/models.py), managed via the /api/llm/* endpoints. Each
# adapter (project/app/services/llm/) is handed its key explicitly rather than
# reading the environment itself; the env vars below remain the fallback when
# no key is stored in the DB (see project/app/services/llm/config.py):
#   claude   -> ANTHROPIC_API_KEY (or CLAUDE_API_KEY, aliased in config.py)
#   chatgpt  -> OPENAI_API_KEY
#   deepseek -> DEEPSEEK_API_KEY
#   groq     -> GROQ_API_KEY   (free tier -- https://console.groq.com)

# Grounding verifier strictness for generated outreach copy (MUS-22):
#   off | standard (default) | strict. See project/app/services/verify.py.
COPY_VERIFY_LEVEL = os.environ.get("COPY_VERIFY_LEVEL", "standard")

# HTTP Basic Auth credentials guarding the 3 LLM configuration endpoints
# (/api/llm/catalog/, /api/llm/config/, /api/llm/config/test/) -- see
# project/app/authentication.py. Unlike DJANGO_SECRET_KEY, this is NOT
# required at Django boot: every other endpoint in this app is intentionally
# AllowAny (see SECURITY.md), and these narrower admin endpoints only need
# credentials configured once someone actually calls them. The auth class
# raises a clear 401 if either is unset when a request hits one of the 3 views.
LLM_ADMIN_USERNAME = os.environ.get("LLM_ADMIN_USERNAME", "")
LLM_ADMIN_PASSWORD = os.environ.get("LLM_ADMIN_PASSWORD", "")


# Settings are read from the environment (see .env.example). `.env` is loaded
# above for local/demo convenience; production should set these directly.
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The key that used to be hardcoded here was committed to git and is burned
# -- it must never be reused anywhere.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Copy .env.example to .env (it ships a "
        "freshly generated key for local/demo use) or set your own via the "
        "environment for production."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "project.app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASE_URL selects the backend, e.g. postgres://user:pass@host:5432/dbname
# (docker-compose.yml sets this for the Postgres service). Unset falls back to
# SQLite so the app still runs with zero setup for local dev.

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Magic-link auth (MUS-37) -------------------------------------------------
LOGIN_ALLOWED_EMAILS = {
    e.strip().lower() for e in os.environ.get("LOGIN_ALLOWED_EMAILS", "").split(",") if e.strip()
}
LOGIN_LINK_DELIVERY = os.environ.get("LOGIN_LINK_DELIVERY", "console")  # console | email
LOGIN_TOKEN_TTL_SECONDS = int(os.environ.get("LOGIN_TOKEN_TTL_SECONDS", "900"))
LOGIN_LINK_BASE_URL = os.environ.get("LOGIN_LINK_BASE_URL", "http://127.0.0.1:8000")
LOGIN_RATE_LIMIT_EMAIL = os.environ.get("LOGIN_RATE_LIMIT_EMAIL", "5/hour")
LOGIN_RATE_LIMIT_IP = os.environ.get("LOGIN_RATE_LIMIT_IP", "20/hour")
LOGIN_RESEND_COOLDOWN_SECONDS = int(os.environ.get("LOGIN_RESEND_COOLDOWN_SECONDS", "30"))

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "project.app.exceptions.contract_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.ScopedRateThrottle"],
    "DEFAULT_THROTTLE_RATES": {
        "auth_request_ip": LOGIN_RATE_LIMIT_IP,
        "auth_consume_ip": "60/hour",
        "queue_verify": "120/min",
    },
}
