"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (KEY=value lines) without requiring python-dotenv
_env_file = BASE_DIR / ".env"
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _k, _, _v = _line.partition("=")
            os.environ.setdefault(_k.strip(), _v.strip())

# LLM provider/model/key selection lives in the database (LLMConfiguration,
# see project/app/models.py), managed via the /api/llm/* endpoints. Each
# adapter (project/app/services/llm/) is handed its key explicitly rather than
# reading the environment itself; the env vars below remain the fallback when
# no key is stored in the DB (see project/app/services/llm/config.py):
#   claude   -> ANTHROPIC_API_KEY (or CLAUDE_API_KEY, aliased in config.py)
#   chatgpt  -> OPENAI_API_KEY
#   deepseek -> DEEPSEEK_API_KEY
#   groq     -> GROQ_API_KEY   (free tier -- https://console.groq.com)

# Grounding verifier strictness for generated outreach copy (MUS-22):
#   off | standard (default) | strict. See project/app/services/verify.py.
COPY_VERIFY_LEVEL = os.environ.get("COPY_VERIFY_LEVEL", "standard")

# --- Planner concurrency, retries and timeouts (MUS-26) -----------------------
# How the planner drives the provider during a run. Read here, range-checked and
# handed to the service layer as frozen dataclasses by
# project/app/services/llm/runtime.py -- nothing under services/llm/ reads
# Django settings itself, so those modules stay importable without Django
# configured (the rules eval and the retry unit tests rely on that).
#
# The four retry values duplicate the DEFAULT_* constants in
# services/llm/runtime.py, which in turn re-export retry.py's. That duplication
# is deliberate -- settings must not import app code at settings-load time --
# and it is pinned by a test, so the two cannot drift apart silently.


def _env_number(name, default, parse, expected):
    """Parse a numeric env var, or return ``default`` when it is unset/blank.

    A bare ``int(os.environ.get(...))`` is the pattern the rest of this file
    uses, and it fails the operator twice over: `invalid literal for int() with
    base 10: 'eight'` names neither the variable nor what it wanted, and an
    *empty* value (which is what you get from `.env.example` when someone blanks
    a line out to "take the default") is a hard boot failure rather than the
    default. Both matter more here than for the login knobs, because these seven
    ship pre-filled in `.env.example`.

    Blank is treated as unset on purpose: `OUTREACH_MAX_IN_FLIGHT=` reads as
    "no opinion", and that is also what `${VAR:-}` passthrough in
    docker-compose.yml produces for a variable the operator never set.
    """
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return default
    try:
        return parse(raw)
    except ValueError:
        raise ImproperlyConfigured(f"{name} must be {expected}, got {raw!r}.") from None


def _env_int(name, default):
    return _env_number(name, default, int, "a whole number")


def _env_float(name, default):
    return _env_number(name, default, float, "a number")


OUTREACH_MAX_IN_FLIGHT = _env_int("OUTREACH_MAX_IN_FLIGHT", 8)
OUTREACH_MAX_ATTEMPTS = _env_int("OUTREACH_MAX_ATTEMPTS", 4)
OUTREACH_INITIAL_BACKOFF_S = _env_float("OUTREACH_INITIAL_BACKOFF_S", 0.5)
OUTREACH_MAX_BACKOFF_S = _env_float("OUTREACH_MAX_BACKOFF_S", 30.0)
OUTREACH_BACKOFF_MULTIPLIER = _env_float("OUTREACH_BACKOFF_MULTIPLIER", 2.0)
# Two nested deadlines: one HTTP attempt, and the whole retry loop for one lead.
# The per-lead bound is what stops a single lead holding a semaphore slot (and
# therefore 1/N of the run's throughput) for the length of the retry budget.
OUTREACH_REQUEST_TIMEOUT_S = _env_float("OUTREACH_REQUEST_TIMEOUT_S", 60.0)
OUTREACH_PER_LEAD_TIMEOUT_S = _env_float("OUTREACH_PER_LEAD_TIMEOUT_S", 150.0)

# --- Agentic copy step (MUS-29) ------------------------------------------------
# Gates the tool-calling agent path in phase 3 of plan_outreach(). False means
# the single-shot copy call runs exactly as before — merged agent code is inert
# until an operator opts in. The three budgets bound one lead's loop: provider
# calls, tool executions, and wall-clock seconds (validated against the
# per-request timeout when the planner runtime is built).
OUTREACH_AGENT_ENABLED = (os.environ.get("OUTREACH_AGENT_ENABLED") or "").strip().lower() in (
    "1",
    "true",
    "yes",
)
OUTREACH_AGENT_MAX_STEPS = _env_int("OUTREACH_AGENT_MAX_STEPS", 6)
OUTREACH_AGENT_MAX_TOOL_CALLS = _env_int("OUTREACH_AGENT_MAX_TOOL_CALLS", 8)
OUTREACH_AGENT_PER_LEAD_TIMEOUT_S = _env_float("OUTREACH_AGENT_PER_LEAD_TIMEOUT_S", 300.0)


# Settings are read from the environment (see .env.example). `.env` is loaded
# above for local/demo convenience; production should set these directly.
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The key that used to be hardcoded here was committed to git and is burned
# -- it must never be reused anywhere.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Copy .env.example to .env (it ships a "
        "freshly generated key for local/demo use) or set your own via the "
        "environment for production."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "project.app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASE_URL selects the backend, e.g. postgres://user:pass@host:5432/dbname
# (docker-compose.yml sets this for the Postgres service). Unset or blank falls
# back to SQLite so the app still runs with zero setup for local dev. Blank must
# count as unset: .env.example ships a blank DATABASE_URL line, so a verbatim
# `cp .env.example .env` exports an empty string, and dj_database_url.config()
# treats that as present — skipping its default and returning the dummy backend.

_database_url = os.environ.get("DATABASE_URL", "").strip()
DATABASES = {
    "default": dj_database_url.parse(
        _database_url or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Magic-link auth (MUS-37) -------------------------------------------------
LOGIN_ALLOWED_EMAILS = {
    e.strip().lower() for e in os.environ.get("LOGIN_ALLOWED_EMAILS", "").split(",") if e.strip()
}
LOGIN_LINK_DELIVERY = os.environ.get("LOGIN_LINK_DELIVERY", "console")  # console | email
LOGIN_TOKEN_TTL_SECONDS = int(os.environ.get("LOGIN_TOKEN_TTL_SECONDS", "900"))
LOGIN_LINK_BASE_URL = os.environ.get("LOGIN_LINK_BASE_URL", "http://127.0.0.1:8000")
LOGIN_RATE_LIMIT_EMAIL = os.environ.get("LOGIN_RATE_LIMIT_EMAIL", "5/hour")
LOGIN_RATE_LIMIT_IP = os.environ.get("LOGIN_RATE_LIMIT_IP", "20/hour")
LOGIN_RESEND_COOLDOWN_SECONDS = int(os.environ.get("LOGIN_RESEND_COOLDOWN_SECONDS", "30"))

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "project.app.authentication.SessionAuthenticationWith401",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "project.app.exceptions.contract_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.ScopedRateThrottle"],
    "DEFAULT_THROTTLE_RATES": {
        "auth_request_ip": LOGIN_RATE_LIMIT_IP,
        "auth_consume_ip": "60/hour",
        "queue_verify": "120/min",
    },
}

# Console delivery of the sign-in link is the demo path, which means the link
# has to actually reach the server log. Django's default logging attaches a
# handler to the `django` logger only, so an INFO record from `project.app`
# falls through to logging's last-resort handler (WARNING and above) and is
# silently dropped -- `docker compose up` would print nothing to paste.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "project.app": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
        },
    },
}

# --- Triage queue (MUS-39) ----------------------------------------------------
TRIAGE_UNDO_WINDOW_SECONDS = int(os.environ.get("TRIAGE_UNDO_WINDOW_SECONDS", "300"))
TRIAGE_SNOOZE_ON_ACTIVITY_BACKSTOP_DAYS = int(
    os.environ.get("TRIAGE_SNOOZE_ON_ACTIVITY_BACKSTOP_DAYS", "14")
)
TRIAGE_TIMEZONE = os.environ.get("TRIAGE_TIMEZONE", "UTC")
